import typing as tp

K = tp.TypeVar("K")
V = tp.TypeVar("V")

class PyBTreeMap(tp.Generic[K, V]):
  def __init__(
      self, other: tp.Union[tp.Mapping[K, V], tp.Iterable[tp.Tuple[K, V]], None] = None
  ) -> None: ...
  def insert(self, key: K, value: V) -> tp.Optional[V]: ...
  def get(self, key: K) -> tp.Optional[V]: ...
  def remove(self, key: K) -> tp.Optional[V]: ...
  def contains_key(self, key: object) -> bool: ...
  def nth(self, n: int) -> tp.Optional[tuple[K, V]]: ...
  # fn len(&self) -> usize
  def len(self) -> int: ...
  # fn is_empty(&self) -> bool
  def is_empty(self) -> bool: ...
  # fn clear(&mut self)
  def clear(self) -> None: ...
  # fn keys(slf: PyRef<'_, Self>) -> PyBTreeKeyIterator
  def keys(self) -> tp.KeysView[K]: ...
  # fn values(slf: PyRef<'_, Self>) -> PyBTreeValueIterator
  def values(self) -> tp.ValuesView[V]: ...
  # fn items(slf: PyRef<'_, Self>) -> PyBTreeIterator
  def items(self) -> tp.ItemsView[K, V]: ...
